public/css/index.css
views/index.pug

Have just added a few bootstrap classes.

minor UI changes

---

public/css/loader.css
public/js/index.js

Hi! I would love to contribute with the following changes:
- centered loader
- hide result while fetching API
- extract elements to variables
Looking forward to your feedback

Fix: center loader and hide result while fetching API

---

CONTRIBUTE.MD
README.md
public/css/index.css
public/css/loader.css
public/js/index.js
routes/api.js

Removed the scroll bars on the x and y plane. Centered the "loading" image.

fixed minor layout items

---

Procfile
nest-cli.json
package-lock.json
package.json
src/main.ts

This PR solves issue #62 
Issue:
Heroku App won't launch properly due to missing config.

Fix heroku app

---

public/js/index.js
views/index.pug

- Added the functionality of enter key press event when the is on input tab for good user experience.
- major bug fix -> result shows url is invalid even if url is valid. This problem arises after user encounters first invalid url.
- Happy Hacking ;)

added on enter keypress event, bug fix:url invalid

---

README.md

This pull requests solves issue #70 which is very crucial for new people coming on repository.
Earlier
here , 
```
node app.js
```
wont' work now, it should get updated

Updating Important Changes in README

---

CODE_OF_CONDUCT.md

I have added the CODE_OF_CONDUCT.md file according to #68

added CODE_OF_CONDUCT.md file

---

views/index.pug

You might want to update the gif on the README as well.

Fixes a typo on the index.pug file

---

public/css/index.css
views/index.pug

@origranot Please review my changes.

center div page horizontally and vertically

---

README.md
package-lock.json

I am new to Hacktoberfest and was trying to contribute in the simplest way possible. Hopefully I will be of more help later as well.

Added more ideas and made readme more lively

---

CONTRIBUTE.MD
README.md

I found some typos in CONTRIBUTE.md and README.md. Corrected them

Fixed typos in CONTRIBUTE.md and README.md

---

frontend/package-lock.json
frontend/package.json
frontend/src/routes/index.tsx
package-lock.json
package.json

With reference to issue #112 , made the changes in the new framework and added the animation

Added the confetti animation along the sides

---

frontend/src/routes/index.tsx

rectified spelling mistake

---

frontend/src/routes/index.tsx

When entering an URL and pressing `Enter` nothing happens but it should, this PR fix the handler to trigger the shortener action.

Fix keypress handler

---

README.md

Changed "I've" to "I". You wouldn't use a verb in this case :)

Grammatical change

---

.github/workflows/CI.yml

Change branch from main to master

fix: update CI.yml

---

frontend/src/components/shortener-input/handleShortener.ts
frontend/src/routes/index.tsx

fix: frontend not building

---

.github/workflows/CI.yml

Add hook for manual dispatch
Change prettier command to fmt.check

feat: add hook to workflows

---

.github/workflows/CI.yml
frontend/src/components/shortener-input/handleShortener.ts
frontend/src/components/shortener-input/shortener-input.tsx
frontend/src/routes/index.tsx

Fixing the bug on the submit button

fix: Submit button won't work correctly

---

.editorconfig
.husky/pre-commit
package-lock.json
package.json
url-shortener.code-workspace

Added husky to run linters on pre-commit.
Added lint-staged package to help husky on staged files.
Added .editorconfig to enforce codestyle (using EditorConfig VSCode Extension)

Add husky and lint-staged

---

backend/package-lock.json
backend/package.json
frontend/package-lock.json
frontend/package.json
package-lock.json
package.json
url-shortener.code-workspace

Renamed workspace folders to reduced.to
Renamed package names to reduced.to
Removed postinstall scripts

update code-workspace and package names

---

package.json

Add .tsx file extension to fmt command (prettier)

add tsx to prettier

---

backend/package-lock.json
backend/package.json
backend/src/app.module.ts
backend/src/cache/cache.module.ts
backend/src/cache/cache.service.ts
backend/src/shortener/shortener.service.spec.ts
backend/src/shortener/shortener.service.ts
package-lock.json
package.json

Closes https://github.com/origranot/reduced.to/issues/119

test: add tests to shortener service

---

frontend/package-lock.json
frontend/src/components/shortener-input/shortener-input.tsx

Added tailwind class to remove focus border.

fix(bug): removed input focus border

---

frontend/src/components/theme-switcher/theme-switcher.css
frontend/src/components/theme-switcher/theme-switcher.tsx
frontend/src/routes/index.tsx
frontend/src/routes/layout.tsx
frontend/tailwind.config.js

Added light/dark themes.
Preview:
Closes #83

feat: Theme switch

---

frontend/src/components/router-head/theme-script.tsx

Fix the theme switcher on the first time the page loads.

Fix the theme switcher

---

frontend/src/components/qr-code/qr-code.tsx
frontend/src/routes/index.tsx

QR colors were not updated according to the selected theme.
Added a mask and increased QR size

fix: incorrect QRCode theme

---

README.md

The links in Table Of Contents were not working, which has been fixed now!

docs(Readme): Fixed Links in TOC

---

frontend/src/components/router-head/router-head.tsx
frontend/src/routes/index.tsx

Added descriptive meta tags through the route component, so we can manage different meta tags on any route in the future

feat: add descriptive SEO

---

frontend/public/robots.txt
frontend/public/sitemap.xml
frontend/src/components/theme-switcher/theme-switcher.tsx
frontend/src/entry.ssr.tsx
frontend/src/entry.static.tsx
frontend/src/root.tsx
frontend/src/routes/index.tsx

Updated canonical URL that was pointing to qwik.builder.io instead of reduced.to
Also added lang="en" attr to html tag and removed from body to improve SEO
Added missing tags for better SEO
Fixed aria content
Current Web Score with these changes:

More SEO Improvements

---

frontend/src/components/shortener-input/shortener-input-btn.tsx
frontend/src/components/theme-switcher/theme-switcher.tsx
frontend/src/global.css
frontend/src/root.tsx
frontend/tailwind.config.js

1. Changed theme from winter to light.
2. Add google verification meta tag.
3. Change the background color of the waves in the light mode.

change theme to light and added google verification

---

backend/package-lock.json
backend/package.json
backend/src/app.module.ts
backend/src/config/config.factory.ts
backend/src/config/config.module.ts
backend/src/config/config.service.spec.ts
backend/src/config/config.service.ts
backend/src/main.ts
package-lock.json
package.json

- Removed unused npm packages that are not in use (root folder).
- Added a config service (including a root test file)

added config and removed unused packages

---

frontend/src/components/router-head/theme-script.tsx
frontend/src/components/theme-switcher/theme-switcher.css
frontend/src/components/theme-switcher/theme-switcher.tsx
frontend/src/global.css
frontend/src/routes/index.tsx
frontend/tailwind.config.js

- **Yes, I just changed the theme switcher input for a button.**
- **Yes, I invested 5 hours on my life on this.**
- **Yes, I had to recreate all the styles.**
**_Because this thing gave me anxiety_**

Convert theme switcher into button

---

backend/package-lock.json
backend/package.json
backend/src/app.module.ts
backend/src/config/config.factory.ts

Fixes #235 
Added the `@nestjs/throttler` module and also used the config module to get the values form the env values, while default value is also provided in the config factory.

feat: Implement rate limit

---

frontend/src/components/router-head/theme-script.tsx

Reduced the times we access directly to the DOM while loading the theme on ThemeScript

Reduce DOM access ThemeScript

---

package-lock.json
package.json

- Fixed the start:prod script
- Removed unnecessary npm dependencies from root package.json

fix: start script from backend

---

.prettierrc.json
backend/.prettierrc.json
backend/src/app.controller.ts
backend/src/shortener/__mocks__/shortener.service.ts
backend/src/shortener/shortener.controller.spec.ts
backend/src/shortener/shortener.controller.ts
frontend/.prettierrc.json
frontend/src/components/alert/alert.tsx
frontend/src/components/github-button/github-button.tsx
frontend/src/components/github-button/utils.ts
frontend/src/components/qr-code/handleQRCode.ts
frontend/src/components/qr-code/qr-code.tsx
frontend/src/components/shortener-input/handleShortener.ts
frontend/src/components/shortener-input/shortener-input-btn.tsx
frontend/src/components/theme-switcher/theme-switcher.tsx
frontend/src/global.css
frontend/src/root.tsx
frontend/src/routes/index.tsx
frontend/src/routes/unknown/index.tsx

- Add basic test cases to our shortener controller
- Change printWidth in prettier config to be 100.

feat: added tests to shortener controller

---

frontend/src/components/shortener-input/handleShortener.ts
frontend/src/root.tsx
frontend/src/routes/[...urlId]/index.tsx
frontend/vite.config.ts

- configured vite config to load env variables

load env into vite

---

frontend/src/components/shortener-input/handleShortener.ts
frontend/src/root.tsx
frontend/src/routes/[...urlId]/index.tsx
frontend/vite.config.ts

This will redefine vite global vars and serve them in local and express server

Enable prod/dev vite settings

---

backend/src/app.controller.ts

- Removed the old functions in the main controller that was used to do ssr from backend.

removed unsued function that was used by old app architecture

---

backend/src/prisma.service.ts
backend/src/users/users.module.ts
backend/src/users/users.service.spec.ts
backend/src/users/users.service.ts

Added users module to handle requests to Users table through Prisma.
Added basic spec for Users module.
Also added Prisma as a service to handle the connection.

feat users service

---

frontend/src/shared/auth.service.ts

I added a service to manage the generated JWT tokens in frontend, it is basic and there is not security involved, but I will work as the base to be improved in the future.

Add service to manage token

---

README.md

Issue link:  https://github.com/origranot/reduced.to/issues/318

Update Report Bug and Request Feature link

---

backend/Dockerfile
backend/tsconfig.json

- Generate the Prisma files in dockerfile before build.

Fix build issue with Prisma

---

backend/src/app.module.ts
backend/src/auth/auth.controller.ts
backend/src/auth/auth.module.ts
backend/src/auth/auth.service.ts
backend/src/auth/dto/login.dto.ts
backend/src/auth/dto/signup.dto.ts
backend/src/main.ts
backend/src/shared/decorators/unique.decorator.ts
backend/src/users/users.service.ts

- Added class-validator to use with our DTO's
- Added a custom unique constraint to check if field on dto is unique on our db

Implemented basic validation on backend

---

backend/.example.env
backend/nest-cli.json
backend/package-lock.json
backend/package.json
backend/src/app.module.ts
backend/src/config/config.factory.ts
backend/src/mail/mail.module.ts
backend/src/mail/mail.service.spec.ts
backend/src/mail/mail.service.ts
backend/src/mail/templates/confirmation.hbs

- Implemented a mail service using nodemailer

implemented a mail service

---

.github/workflows/codeql.yml

Added a codeQL workflow to discover vulnerabilities across the codebase and eradicate them.

Added codeQL vulnerabilities check

---

frontend/src/components/shortener-input/shortener-input.tsx

Hey @origranot,
Since I kind of messed up with commits on PR #345 ISSUE #328 
Please check this commit, it's much cleaner, best practice from Qwik to use useOnDocument instead of the way I initially did it.

Focus search input on slash

---

backend/src/shortener/shortener.controller.ts

Checks if the URL is not already reduced   ==>  Checks if the URL is already reduced

fix comments

---

README.md
backend/.example.env
backend/src/cache/cache.module.ts
backend/src/config/config.factory.ts
docker-compose.dev.yml
docker-compose.prod.yml

- Added password option to external redis store.
- Updated README and docker-compose files

fix(cache): added a password to the redis store

---

.github/workflows/deploy.yml

Changes `checkout` action version

---

backend/.test.env
backend/src/cache/cache.service.spec.ts
backend/src/config/config.factory.ts
backend/src/config/config.module.ts
backend/src/config/config.service.spec.ts
backend/src/config/config.service.ts
backend/src/shortener/shortener.service.spec.ts
backend/src/shortener/shortener.service.ts

- Added unit tests to cache service
- Made a custom .test.env file for testing shortenerService
- Added unit tests to config service.

tests(app): added multiple unit tests cases

---

backend/src/shared/decorators/unique.decorator.spec.ts
backend/src/shared/decorators/unique.decorator.ts

- Added unit tests for the unique decorator.

test(decorator): add unit tests for unique decorator

---

backend/src/shortener/shortener.controller.spec.ts
backend/src/shortener/shortener.controller.ts

- Updated the shortener controller to throw an error if the short url is not exist in the cache.
- Added more test cases for the shortener controller.

test(shortener): add unit tests to shortener controller

---

.github/workflows/deploy.yml
backend/src/shortener/shortener.controller.spec.ts
backend/src/shortener/shortener.controller.ts

- Modified and updated Github deploy workflow

Updated deploy workflow

---

backend/src/auth/auth.service.spec.ts
docker-compose.prod.yml

- Added a clean-up flag to Watchtower.
- Added basic test cases to the authentication service.

test(auth): added basic unit tests to auth service

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/tooltip/tooltip.tsx
frontend/src/routes/[...urlId]/index.tsx

- Migrated to latest Qwik release

deps(qwik): migrate to latest qwik release

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/router-head/router-head.tsx

refactor(router-head.tsx): remove unused useLocation hook and link rel="canonical" tag

chore(frontend): update devDependencies and dependencies

---

backend/package-lock.json
backend/package.json
frontend/src/components/shortener-input/shortener-input.tsx

Slashes fix

---

frontend/src/components/waves/waves.css
frontend/src/routes/index.tsx

style(waves.css): change bottom to top in .waves-div
style(waves.css): move margin-bottom to the end of .waves-div properties
style(index.tsx): remove min-h-screen from parent div
style(index.tsx): change height of child div to be 100vh minus 64px
style(index.tsx): remove justify-start from child div and add flex-1 class to it
style(index.tsx): remove mx-auto from parent div and add it to child div

style(waves.css): change margin-bottom to margin-top in .waves-div

---

backend/src/auth/auth.controller.ts
backend/src/auth/auth.service.spec.ts
backend/src/auth/auth.service.ts
backend/src/novu/novu.service.ts

During my research, I discovered some minor areas that could be improved:
1. Shorten file path.
2. Use UserContext interface instead of 'any'.
3. Remove redundant and unused imports.

Minor fixes

---

.github/workflows/build.yml
.github/workflows/lint.yml
.github/workflows/test.yml

Split workflow into lint, build and test workflow

---

LICENSE
frontend/src/components/use-cookies-alert/use-cookies-alert.tsx
frontend/src/routes/layout.tsx
frontend/src/routes/privacy-policy/index.tsx

feat(use-cookies-alert.tsx): add UseCookiesAlert component
feat(layout.tsx): add UseCookiesAlert component to layout
feat(privacy-policy): add privacy policy page and document head metadata

Add "We use cookies" alert, including a privacy policy.

---

backend/src/shortener/shortener.controller.ts
backend/src/shortener/shortener.service.ts
frontend/src/components/shortener-input/handleShortener.ts
frontend/src/utils/index.ts

1. Use type script types inside js-docs
2. Add return type to fineOne method

Docs and type improvments

---

backend/src/shared/utils/pagination/pagination.ts
backend/src/shared/utils/ttl/ttl.spec.ts
backend/src/shortener/shortener.service.spec.ts
backend/src/users/users.controller.spec.ts
backend/src/users/users.controller.ts
backend/src/users/users.service.spec.ts
backend/src/users/users.service.ts

- Add IPaginationResult interface to shared/utils/pagination/pagination.ts
- Modify findAll method in UsersService to return IPaginationResult
- Modify findAll method in UsersController to return IPaginationResult
- Modify users.controller.spec.ts to test pagination functionality
fix(ttl.spec.ts, shortener.service.spec.ts, users.service.spec.ts): use jest.useFakeTimers() and jest.useRealTimers() to avoid side effects in other tests

feat(users): add pagination support to findAll method

---

backend/src/shortener/dto/shortener.dto.ts

the ttl field in ShortenerDto class is considered valid if it's value is a number, including a negative number, which is an invalid state.
this pr restricts ttl to only positive numbers.

validate ttl is a positive number in ShortenerDto class

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/navbar/navbar.tsx
frontend/src/components/navbar/profile/profile.tsx
frontend/src/components/shortener-input/shortener-input-btn.tsx
frontend/src/components/shortener-input/shortener-input.tsx
frontend/src/global.css
frontend/src/routes/dashboard/layout.tsx
frontend/src/routes/index.tsx
frontend/src/routes/register/verify/index.tsx

Reverts origranot/reduced.to#413
@izdotnet Somehow there are a lot of things that messed up after using it for a while.
Please test it a bit more before you open a PR again.

Revert "Updated DaisyUI to 3.0 and fixed breaking changes."

---

docker-compose.prod.yml

chore(docker-compose.prod.yml): add volume to postgres service

---

.eslintrc
package-lock.json
package.json

fix: add eslint and prettier to root workspace
chore(package.json): update lint-staged package version to 13.2.3 to match the latest version

chore(eslint): add ESLint configuration file to enforce linting rules

---

README.md

-  Added preview GIF to assets folder on root repo
- updated the documentation to include the Preview GIF for users

add preview GIF to assets and docs

---

apps/docs/docs/overview.md

fixed typo

---

README.md

Updates Docs

---

apps/frontend/src/components/navbar/navbar.tsx

Fixes : #479 Right Margin In Toggle Switch

Fixes : #479 Right Margin In Toggle Switch

---

apps/frontend/src/routes/register/index.tsx

fix: Resolve password show/hide button overlapping with password input(#503)

---

apps/frontend/src/routes/dashboard/layout.tsx

Closes https://github.com/origranot/reduced.to/issues/510

fix: close drawer on link click

---

apps/frontend/src/components/navbar/navbar.tsx
apps/frontend/src/components/navbar/profile/profile.tsx
apps/frontend/src/components/navbar/resources/resources.tsx

This PR introduces a new feature that enhances our application's user interface and functionality by adding a dropdown menu with a placeholder option, specifically designed to improve the user experience when interacting with the Report button. This new dropdown menu will provide users with a more intuitive and organized way to access and select reporting options, making the process smoother and more user-friendly.
Related to: https://github.com/origranot/reduced.to/issues/520

feat: add resources dropdown

---

apps/docs/docusaurus.config.js

fixed #465
checked on locally it's working fine. @origranot plz check

issue bug link not working on docs [fixed]

---

CODE-OF-CONDUCT.md

Resolved #544 
Added the CODE-OF-CONDUCT to the repository

[DOCS] Add CODE-OF-CONDUCT to the repository

---

README.md

A minor change made in order to make the documentation more professional-looking and consistent throughout its length.

docs: improved consistency with existing documentation

---

apps/frontend/Dockerfile

Better frontend docker file

---

apps/backend/src/shortener/shortener.service.ts
apps/frontend/src/components/dashboard/links/link-modal/link-modal.tsx
apps/frontend/src/components/dashboard/links/link/link.tsx

and add 23:59:59 to expirationTime
and make link in table clickable with open a new tab

small fixes for #667

---

apps/frontend/src/components/dashboard/links/link/link.tsx

Closes #693 .
**changes preview:**

fix url overlaping

---

apps/frontend/src/components/dashboard/analytics/contries-chart/countries-chart.tsx
apps/frontend/src/components/dashboard/links/link/link.tsx

Closes https://github.com/origranot/reduced.to/issues/773

fix: copy link now copies the short link

---

apps/frontend/src/components/dashboard/analytics/contries-chart/countries-chart.tsx
apps/frontend/src/components/dashboard/links/link-modal/link-modal.tsx

Closes https://github.com/origranot/reduced.to/issues/772

fix: allow dashes in url key

---

apps/frontend/tailwind.config.js
package-lock.json
package.json

Closes https://github.com/origranot/reduced.to/issues/788

feat: update Qwik version

---

apps/frontend/src/components/dashboard/links/link/link.tsx
libs/prisma/src/migrations/20240711043718_init/migration.sql

Dates added for mobiles device

Dates added for mobiles device

---

apps/backend/tsconfig.json
apps/tracker/tsconfig.json
libs/config/tsconfig.json
libs/logger/tsconfig.json
libs/prisma/tsconfig.json
libs/queue-manager/tsconfig.json
libs/safe-url/tsconfig.json
libs/subscription-manager/tsconfig.json
libs/utils/tsconfig.json

@origranot  Please tell me if you see any problem with this config change

Add the src to all the tsconfig filed include property
